//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace login
{
    using System;
    using System.Collections.Generic;
    
    public partial class uzytkownicy
    {
        public int Id { get; set; }
        public string login { get; set; }
        public string haslo { get; set; }
        public string pytanie { get; set; }
        public string odpowiedz { get; set; }
    }
}
